### ISSUE TITLE
Support error handle

### ISSUE THREAD

**Issue by Waniusza** [knalli/angular-vertxbus#106]
Hi!

I'm using your library and it's great, thanks!
But now, I got problem.
After adding access control on server side, if I got error response ('access_denied'), my SockJs doesn't know what to do with that, because  vertx.EventBus doesn't support handling error:

```
    that.onopen = null;
    that.onclose = null;
    that.onerror = null;
```

You did great job to support onopen and onclode methods right there:
https://github.com/knalli/angular-vertxbus/blob/43626aade7b49abccf2f5609c30589ef66bf78c9/dist/angular-vertxbus.js#L810

But what about onerror? 
Is it on develop stage?

**Comment by knalli** [comment]
Well,

I have never thought about this. Is this onerror new?

PS: I’m welcome for any contributions! :)

Regards,
-Jan

**Comment by Waniusza** [comment]
I use old version of vertxbus.js (from may or june).
Now I see there is no onerror function, and others are deprecated.
this.sockJSConn.onmessage method got something like:
```
   if (self.handlers[json.address]) {  .... } 
   else if (self.replyHandlers[json.address]) { .... }
   else {
        if (json.type === 'err') {
          self.onerror(json);
        } else {
          console.warn('No handler found for message: ', json);
        }
      }
    
```
And now they support now version of eventbus with a bit different API (for example, now there is no readyState() method):
https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/client/vertx-eventbus.js

I wish to help you, but I'm not advanced enough in programming.

Are you going to support new vertxBus library?

**Comment by knalli** [comment]
I will put it on the list. But any contribution has the chance of being faster ;)

**Comment by Waniusza** [comment]
Thanks, I will try to help :)
