### ISSUE TITLE
useSockjsOptions not supported

### ISSUE THREAD

**Issue by dingus1** [knalli/angular-vertxbus#107]
I want to disabled all transport protocols except websocket, but I can't do it using useSockjsOptions function.
It's because of instancing EventBus passing 3 arguments except 2.
```javascript
new this.EventBus(url, undefined, this.options.sockjsOptions);
```
maybe it should be 
```javascript
new this.EventBus(url, this.options.sockjsOptions);
```
or maybe i used old version of eventbus.js
````javascript
vertx.EventBus = function(url, options) {
...
}
````

**Comment by knalli** [comment]
@dingus1 .. No, that's looking like a bug 🐛. There is no 3rd argument. Will be fixed soon.
