### ISSUE TITLE
setting authentication header for websocket API

### ISSUE THREAD

**Issue by manuknkra** [knalli/angular-vertxbus#155]
How to set authentication header for websocket API?

**Comment by knalli** [comment]
As far as I know, this is not possible because SockJS is not providing such a feature. Therefore Vert.x supports authentication via regular messages (both v2 + v3).

**Comment by knalli** [comment]
I've added a demo using vertx headers in the demo -- within release 6! Have a look at `authHandler`

Unfortunately, my release 5 was really broken.

https://github.com/knalli/angular-vertxbus/blob/a3445fdc3f7c33644c1a447fc85872cf7254d060/test/e2e/web/app.js#L46
