### ISSUE TITLE
service.unregister(...) must be passed the same callback as service.register(...) to work

### ISSUE THREAD

**Issue by HugoCrd** [knalli/angular-vertxbus#203]
Hi!

### Subject of the issue
When unsubscribing from a handler, `EventBusDelegate` tests that given callback is part of `callbackMap`.

This enforce developer to give the exact same callback to both `.register()` and `.unregister()`.
I may have missed something but this behaviour seems odd to me.

See this line : https://github.com/knalli/angular-vertxbus/blob/a3445fdc3f7c33644c1a447fc85872cf7254d060/src/lib/service/delegate/EventBusDelegate.js#L207

### Your environment
Angular 1.5.x
Firefox, Chrome, Safari

### Steps to reproduce

This DOES NOT unsubscribe : 
```javascript
vertxEventBusService.on(`my-address`, (err, response) => {// DO SOMETHING });
vertxEventBusService.un(`my-address`, (err, response) => {// DO SOMETHING ELSE });
```

This DOES unsubscribe : 
```javascript
const cb = (err, response) => {// DO SOMETHING };
vertxEventBusService.on(`my-address`, cb);
vertxEventBusService.un(`my-address`, cb);
```
There may be a good reason to that (that I can't see myself) but in this case this should be clearer in documentation.

Anyway thanks for this awesome module!

**Comment by knalli** [comment]
That is a correct behaviour. 

```js
vertxEventBusService.on(`my-address`, (err, response) => {// DO SOMETHING });
vertxEventBusService.un(`my-address`, (err, response) => {// DO SOMETHING ELSE });
```

This are not the same functions, they are two different instances of the same looking function header and body.

Just like `{} !== {}`.

**Comment by HugoCrd** [comment]
> This are not the same functions, they are two different instances of the same looking function header and body.

I'm aware of that and I thought that was the correct way to go : passing 2 different callbacks to these functions.

I understand now that this is made to unregister the handler which created this registration. (As said in : http://vertx.io/docs/jsdoc/module-vertx-js_message_consumer-MessageConsumer.html#unregister).

The problem now is : I do not have any callback when unregister is done right?

**Comment by knalli** [comment]
I don't get it.

```js
vertxEventBusService.on(`my-address`, fn)
vertxEventBusService.un(`my-address`, fn)
```

will working only if fn is the same object. Otherwise it is impossible to unregister the handler anyway. How?

> I understand now that this is made to unregister the handler which created this registration. (As said in : http://vertx.io/docs/jsdoc/module-vertx-js_message_consumer-MessageConsumer.html#unregister).

Well, this is an API not related to this project. I'm not implementing a message consumer interface.

> The problem now is : I do not have any callback when unregister is done right?

What do you mean?

In a nutshell (referring https://github.com/knalli/angular-vertxbus#architecture-details):

```js
const callback = () -> {
  console.log('I am a handler');
};

// A
vertxEventBusService.on('address', callback); // after this, one handler registered
vertxEventBusService.un('address', callback); // after this, no handler registered

// B
const unregister = vertxEventBusService.on('address', callback); // after this, one handler registered
unregister(); // after this, no handler registered
```

**Comment by HugoCrd** [comment]
Ok I get it.

```
vertxEventBusService.on('address', callback); // after this, one handler registered
vertxEventBusService.un('address', callback); // after this, no handler registered
```

What confused me was that `callback` parameter in `.unregister` is not really a callback for `.unregister` function but a reference to `register` handler. I was expecting `.unregister` to call it after finishing because I wasn't aware of that.

But ok, got it, I think we can close this. Thanks for your time!
