### ISSUE TITLE
Last version with vertx 2.x support

### ISSUE THREAD

**Issue by joh-klein** [knalli/angular-vertxbus#247]
Hi,
just wondering, since I have to support a vertx 2.x backend, what is the last version of your wrapper, that would work with that?
Thanks for all your work!

**Comment by knalli** [comment]
* e06515b7a7b652d27c111390126eb975819cc19d introduces v3.2.0
* f56b4a64d906a43e7f1a1953ce32e37f66e191e8 introduces v3.0.0 initially

So, [angular-vertxbus 2.0.4](https://github.com/knalli/angular-vertxbus/releases/tag/2.0.4) is the last release supporting a v2.~
