### ISSUE TITLE
Eventbus not working on android phone

### ISSUE THREAD

**Issue by MoePad** [knalli/angular-vertxbus#254]
### Eventbus not working on android phone
I'm using the angular-vertxbus to connect to my server. With the desktop browser there is no problem. The problem only occurs on android phones (I have two; one with android 5.0.0. and one with android 6+).

### My environment
```
  "dependencies": {
    "angular": "1.6.4",
    "angular-material": "1.1.3",
    "angular-aria": "1.6.4",
    "angular-route": "1.6.4",
    "angular-loader": "1.6.4",
    "angular-mocks": "1.6.4",
    "angular-resource": "1.6.4",
    "mobile-angular-ui": "1.3.4",
    "vertx3-eventbus-client": "3.2.1",
    "angular-vertxbus": "6.2.0",
    "ngCordova": "x.x.x",
    "angular-lodash": "x.x.x",
    "ng-device-detector": "x.x.x",
    "angular-uuid-service": "x.x.x",
    "angular-animate": "x.x.x",
    "hammerjs": "x.x.x",
    "re-tree": "x.x.x",
    "ngstorage": "x.x.x",
    "nsPopover": "x.x.x",
    "ngDialog": "x.x.x",
    "angular-i18n": "x.x.x",
    "google-maps": "3.2.1",
    "jquery": "3.2.1",
    "sockjs-client": "1.0.3"
  }
```

* which browser and its version: desktop: firefox (latest); android: inappbrowser of cordova/phonegap

### Log
The actual IP is replaced by XXXXX. It's working on the desktop, so the IP/port is not the problem anyway.
```
I/chromium(24689): [INFO:CONSOLE(14525)] "[Vert.x EB Stub] Enabled", source: file:///android_asset/www/bower_components/angular/angular.js (14525)
I/chromium(24689): [INFO:CONSOLE(14525)] "[Vert.x EB Stub] Enabled: connecting 'http://XXXXXXXX/eventbus'", source: file:///android_asset/www/bower_components/angular/angular.js (14525)
I/chromium(24689): [INFO:CONSOLE(14525)] "[Vert.x EB Stub] Reconnect in 10000ms", source: file:///android_asset/www/bower_components/angular/angular.js (14525)
I/chromium(24689): [INFO:CONSOLE(14525)] "[Vert.x EB Stub] Reconnect in 10000ms", source: file:///android_asset/www/bower_components/angular/angular.js (14525)
I/chromium(24689): [INFO:CONSOLE(14525)] "[Vert.x EB Stub] Enabled: connecting 'XXXXXXX'", 
source: file:///android_asset/www/bower_components/angular/angular.js (14525)
I/chromium(24689): [INFO:CONSOLE(14525)] "[Vert.x EB Stub] Reconnect in 10000ms", source: file:///android_asset/www/bower_components/angular/angular.js (14525)
I/chromium(24689): [INFO:CONSOLE(14525)] "[Vert.x EB Stub] Reconnect in 10000ms", source: file:///android_asset/www/bower_components/angular/angular.js (14525)
```

Do you have any idea/recommendation how to troubleshot this? Or even a solution? I tried almost a whole day to figure out the problem. So far, I have no solution

**Comment by knalli** [comment]
Maybe an issue with CORS, related to you entrypoint at `file:///`?

**Comment by MoePad** [comment]
Thanks for the quick reply! I'm not really sure what you mean by CORS and the entrypoint. This is my first javascript / angular project (although I have years of expierence with Java and C/C++).

I'm using the default configuration from almost everything - at least regarding the vertx stuff.

The configruation of the vertxEventBusProvider is as following:
`vertxEventBusProvider.enable().useReconnect().useUrlServer(globalConfigJson.eventBusServerUrl).useUrlPath('/eventbus').useDebug(true);`

Can I get more/more detailed logs somehow? Or is there a possibility to test the basic stuff?

**Comment by knalli** [comment]
Well, depending on your setup (running on a local server or running on `file://`), your browser (as well as a web view) will check whether accessed server/endpoint allows cross origin requests. Let's say: Is a page of host X allowed to access host Y? Because of security, this cannot be changed on the app side (that would be silly :) ), but on server side. In that case the Vert.X instance itself.

You should verify this in the debugger view (network panel), because the request in question will probably have a cors options prefly counterpart, maybe also paired with an error message.

See also https://github.com/vert-x3/vertx-examples/blob/2e2bf62b0f7b92f26dae794b3806f691f0cae628/web-examples/src/main/java/io/vertx/example/web/cors/Server.java

See also http://stackoverflow.com/questions/38996253/cors-issue-in-vertx-application-not-working

**Comment by MoePad** [comment]
Ok, it seems that you are right. With your hints I troubleshot the problem to 

```
  try {
    self.xhr.send(payload);
  } catch (e) {
    self.emit('finish', 0, '');
    self._cleanup(false);
  }
```
in sockjs.js:1610 and I'm also seeing the failing xhr requests in the network tab. 

What I'm wondering is that everything is working fine in the desktop browser. Only both of the android phones have this issue...

I will try to fix this and come back here to post the solution if I find any.

**Comment by knalli** [comment]
... because in your environment (local in browser and on the phone) are not the same when developing with cordova/phonegap. See also "cordova + cors"

**Comment by MoePad** [comment]
Ok, it's working now. Thanks a lot!

I needed to install the whitelist plugin https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/ and add the following line to the config.xml:
<access origin="*" />
<allow-navigation href="*"/>

Seriously, you saved my day. Is there any possibility to pay you a beer or something (e.g. a donate option)? I would have spend lots of days for this issue without your help.

**Comment by knalli** [comment]
Ha, thank you. 🍺  Well, no donations. 

Have a nice day ;)

**Comment by MoePad** [comment]
Too bad! Then I hope that your next beer at least tastes twice as good as usual ;)

Thanks again and a nice day for you, too!
