### ISSUE TITLE
Compatible with angular.js 1.6.4?

### ISSUE THREAD

**Issue by leolux** [knalli/angular-vertxbus#260]
I like to update angular-vertxbus to version 6.2.0 and angular to version 1.6.4. I am not sure if the wrapper is compatible with angular 1.6.4 because the bower dependency seems to be broken:
`"angular": ">=1.2 <=1.6"`

When I enter "bower update" it tells me that the best option for angular would be version 1.5.11. What is about the latest version 1.6.4?

**Comment by knalli** [comment]
Sigh.. I don't know why this not working (any more). As `>=1.2 <=1.6` is describing: angular-vertxbus should work with AngularJS 1.6 including.

In another project I'm using `< 1.7`, so I will update this.

@leolux So long prepare a fixed resolution.

**Comment by knalli** [comment]
6.2.0 [adds](https://github.com/knalli/angular-vertxbus/commit/f383f29f3cd57c4d932ac87e620e2cf0cae81e8d) official support for AJS 1.6 -- will say I have added an additional test scope without failures.
