### ISSUE TITLE
Documentation incomplete for the "headers" object

### ISSUE THREAD

**Issue by leolux** [knalli/angular-vertxbus#261]
"header" is an optional parameter for the send() function of the vertxBus / vertxBusService. In older versions of this project the place of this parameter was used to define a send timeout. How to accomplish this with the "headers" object`? 

### environment
* version of angular-vertxbus: 6.2.0

**Comment by knalli** [comment]
@leolux  Which one? Maybe link to the code directly...

**Comment by knalli** [comment]
Fixed (doc issue).
