### ISSUE TITLE
Adapt to vertx3-eventbus-client 3.5.0

### ISSUE THREAD

**Issue by leolux** [knalli/angular-vertxbus#273]
The current release includes the following changes

**Real code:**
https://github.com/vert-x3/vertx-web/blob/3.5.0/vertx-web/src/client/vertx-eventbus.js

**Diff:**
https://github.com/vert-x3/vertx-bus-bower/commit/32065d55128b5861524573d40a0e37a2962087df

**Changelog:**
https://github.com/vert-x3/wiki/wiki/3.5.0-Release-Notes

**Relevant issue:**
https://github.com/vert-x3/vertx-bus-bower/pull/10

**Comment by knalli** [comment]
Oh, they have added reconnect support.

**Comment by knalli** [comment]
Please try with npm angular-vertxbus@6.4.0-beta1

**Comment by leolux** [comment]
Ok, I am testing on the following versions:
angular 1.6.4
angular-vertxbus 6.4.9-beta1
vertx3-eventbus-client 3.5.1

The connection works but when I switch of the wifi on my client the vertx-eventbus.system.disconnected does not get triggered. When enabling wifi again the reconnection does not happen because the 60 seconds idle timeout of the server already destroyed the tcp connection.

I have to check in the vertx forum if the websocket reconnection is possible after the idle timeout of the http server.

Should I remove the What about the method  vertxEventBus.reconnect(true)

**Comment by knalli** [comment]
> The connection works but when I switch of the wifi on my client theevent vertx-eventbus.system.disconnected does not get triggered. 
Currently, that's is working as expected -- it's simply ignore the disconnect as it will be handled by the EventBus itself. Originally, `disconnected` was meant to be the intentional disconnect. Atm, it will be fired if a close has been managed by angular-vertxbus.

My test case was so far just simple: Startup vertx server and startup demo web client app. Kill the vertx server and watch the offline logs. Restart vertx server and verify reconnection.

```
# within angular-vertxbus
# pre
npm run -s clean
npm run -s compile-dist
npm run -s install-it-vertx-server
# run
npm run -s start-it-vertx-server
npm run -s start-it-web-server
# visit http://localhost:3000
# kill vertx-server
# re-run
npm run -s start-it-vertx-server

**Comment by knalli** [comment]
> reconnect(true)

This will close the underlying instance instantly. That has nothing to do with the new feature.

**Comment by leolux** [comment]
Would it be possible to fire a separate event for reconnects? There seems to a functin already:
https://github.com/vert-x3/vertx-web/blob/3.5.0/vertx-web/src/client/vertx-eventbus.js#L126

**Comment by leolux** [comment]
The reconnect works as expected in both directions so it doesn't matter if the client looses connection or the server.

**Comment by knalli** [comment]
Do you mean a simple `onreconnect` driven event, separated from connect and disconnect?

**Comment by leolux** [comment]
Yes, exactly.

**Comment by knalli** [comment]
See above changes, see angular-vertxbus@6.4.0-beta2

**Comment by leolux** [comment]
Great work!
The new "reconnected" event gets fired as expected in my test. I think the implementation of this issue is feature complete.

**Comment by knalli** [comment]
6.4.0 available
