### ISSUE TITLE
vertxEventBusService not working after 6 seconds disconnection when using explicit reconnect approach

### ISSUE THREAD

**Issue by leolux** [knalli/angular-vertxbus#274]
### Subject of the issue
I am setting `vertxEventBusProvider.useReconnect(false);` to be able to stop the client from reconnecting automatically at a later point in time because I have a special app which should be connected for only 3 minutes. Withing those 3 minutes reconnects should be possible. Therefore I have to use the explicit reconnect approach:
```
//within the vertx-eventbus.system.disconnected event
reconnectTimer = $interval(function () {
   vertxEventBus.reconnect(true);
}, 4000);
```
and
```
//within the vertx-eventbus.system.connected event
$interval.cancel(reconnectTimer);
```
This explicit reconnect approach seems to work in the first place because the` vertx-eventbus.system.connected` event gets fired after the reconnect happens. But there are several issues after the reconnect:
- `vertxEventBusService.send()` does not reach the server anymore
- `vertxEventBusService.send()` with an expected reply does not respond (neither success nor error)   
- `vertxEventBusService.on()` won't receive any messages from the server
- previously registered handlers won't receive messages anymore

All of these issues appear only if the disconnection takes at least 6 seconds before the client reconnects. It doesn't matter if you register a message handler or send messages to the server before the disconnection.

These issues do not appear when the disconnection takes only 2 seconds. But a reconnect after 2 seconds disconnection introduces another issue: The "disconnected" event gets fired for every incoming message.

Note: everything works fine when using the automatic reconnect feature `vertxEventBusProvider.useReconnect(true);` even after 20 seconds disconnection or more.

### Your environment
* version of angular-vertxbus 6.3.0
* version of angular 1.6.4
* which browser and its version Chrome 61 (mobile)

### Steps to reproduce
The following reproducer is able to show the issues. It uses vertx 3.4.2 and angular-vertxbus 6.3.0 with the latest depedencies.: https://github.com/leolux/angular-vertxbus_reconnect

### Expected behaviour
vertxEventBusService stops working after the reconnect

### Actual behaviour
vertxEventBusService works the same way as when using the automatic reconnection option `vertxEventBusProvider.useReconnect(true);`

**Comment by leolux** [comment]
The explicit reconnect approach would be unnecessary if `vertxEventBus.close();` would work and would stop the reconnection. But it does not.

**Comment by knalli** [comment]
Angular 3.4.2?

Maybe we should disable reconnect when using `vertxEventBus.close()` explicitly. However, this will require some internal "work" I guess.

**Comment by leolux** [comment]
In the reproducer I have angular 1.6.4. I have updated the initial post.
Are you able to reproduce the issue?

**Comment by knalli** [comment]
Not yet. But the current situation is well-documented and flagged as feature. Maybe a design issue. 

https://github.com/knalli/angular-vertxbus/blob/18a2c6325f154946cf50f0702b587bbaa3042023/src/lib/adapter/EventBusAdapter.js#L230-L248

Maybe an additional flag `boolean disableReconnect` is enough.

**Comment by leolux** [comment]
Sounds good!
Currentrly I have a bunch of important work to do which means I am busy for the next 2 or 3 weeks.
