### ISSUE TITLE
Unhandeled Error for expectReply = false

### ISSUE THREAD

**Issue by leolux** [knalli/angular-vertxbus#283]
Currently the promise gets resolved immediately when the user passes the parameter expectReply=false to the send() function: https://github.com/knalli/angular-vertxbus/blob/18a2c6325f154946cf50f0702b587bbaa3042023/src/lib/service/delegate/EventBusDelegate.js#L239

But the send() function might throw an Error: 
https://github.com/vert-x3/vertx-web/blob/3.5.1/vertx-web/src/client/vertx-eventbus.js#L202

This Eror is currently unhandeled by angular-vertxbus. Therefore I have to wrap each send() into a try/catch block to ensure that the Error does not fly through the whole application.

**Comment by knalli** [comment]
Eh.. 🤦‍♂️  Yes, should be fixed.

**Comment by knalli** [comment]
Well.. but why? If the `EventBusDelegate.send()` is using `ensureOpenAuthConnection`/`ensureOpenConnection` internally which ensures the `eventBus.state == EventBus.OPEN`. I wonder when it get into trouble..

**Comment by knalli** [comment]
Anyway: Including beta2, this will also handle this: angular-vertxbus@6.4.0-beta3

This would be the as-is release.

**Comment by leolux** [comment]
I was able to produce the the "INVALID_STATE_ERR" Error serveral times. It is quite easy to produce: Just trigger the send() function right after disconnecting the client from the network. At this point in time the browser hasn't triggered any offline event and the ping interval of the SockJS brige hasn't triggered either. So the app thinks that that the user is online. The way it works is correct because no app should rely on a stable network..

**Comment by knalli** [comment]
As already mentioned, if beta3 is fine, I would ship it.

**Comment by leolux** [comment]
I just watched the changes it it looks fine. The try/catch works perfectly. It is the way I have solved it and tested also.
