### ISSUE TITLE
Event "disconnected" gets fired although the client has no connection to the server

### ISSUE THREAD

**Issue by leolux** [knalli/angular-vertxbus#37]
In the current version 0.11.2 I found this issue:
I receive "vertx-eventbus.system.disconnected" events periodically although the client is not connected to any eventbus. The connection from the client to the vertx server is impossible because the server is not running in my case.

Maybe the framework should check the connection state before broadcasting this event. What would you think?

**Comment by knalli** [comment]
@leolux , yes that would be better. Indeed, I had already seen that issue some time ago, but, unfortunately, was to be short of time.

I've pushed a fix that should avoid multiple events.. what do you think?

**Comment by leolux** [comment]
That was so fast.. thank you! Your push https://github.com/knalli/angular-vertxbus/commit/0f56411df70d754a7722427169f8150aef5e5d2b looks good to me. The internal states object works very well and can easily be extended by further attributes in future, if needed.

Two questions aside about coffee: Do you develop the whole framework in coffee? I do not have skills in coffee script yet. Would you recommend it for serious web developers?

**Comment by knalli** [comment]
> Two questions aside about coffee: Do you develop the whole framework in coffee?

Well, this is only a wrapper library around _vertxbus.js_ and _SockJS_.

>  I do not have skills in coffee script yet. Would you recommend it for serious web developers?

Actually *we are* using CoffeeScript at work. So, yes you can use it seriously. However, just like other technologies, it must fit your need and you have to know what you are doing.

CoffeeScript let's make me less (coding) failures and requires less boiler code (especially when it is coming to short guards/conditions and loops, or string templates, or scopes). And some of the ES6 features are not new for a CoffeeScript user.. but, said to be load and clearly, it is not all the same.

Looking into the future of a coming and rising ES6 (and its usage in AJS 2), perhaps that project will gota rewrite in ES6 and post-transpiled for legacy environments. We will see.

> That was so fast.. thank you! Your push 0f56411 looks good to me.

Okay, I think it will be part of the next release (0.12 or 1.0). I do not think we have to patch this, it isn't a new issue.
