### ISSUE TITLE
initial reply dropped (caught immediately) after recycling the event bus

### ISSUE THREAD

**Issue by Kirk-A** [knalli/angular-vertxbus#38]
This case involves three parties: 
1) the angularjs client, a Cesium map application
2) a SockJSServer which monitors the event bus (derived from the bridge_server.js example verticle)
3) a registered handler to receive and respond to the client's message (derived from the  eventbus_pubsub.js example verticle)

With the client running, after recycling the event bus (both verticles), the reply to client's first message immediately fails, triggering the catch function. Each client transmission thereafter works as expected. Using the FINER message logging, I can observe that the verticle containing the SockJSServer receives and forwards the message, and the verticle registered to receive the message does in fact receive it. The SockJSServer appears to transmit the reply, judging by the byte count of the message. However, the first replier message does not get back to the client.

The messages are time-stamped by both the client and the replier. Successful messages have consistent transmission and reply time-stamps; there is not a synchronization problem (receiving an old reply to a current send). Only the initial reply (to the first message after recycling the event bus) fails to reach the client.

1) The client code excerpt is:
        var now = new Date();
        var ts = now.toISOString();
        vertxEventBusService.send('ping-address', {data: ts + " test for echo " + myICD}, 20).then(function(reply){
            console.log('vertx echo received: ', reply);
        }).catch(function(){
            console.warn('vertx no reply');
        });

2) The modified bridge_server.js example verticle code is:
var vertx = require('vertx');
var console = require('vertx/console');
var server = vertx.createHttpServer()
// Serve the static resources
server.requestHandler(function(req) {
  console.log('request received');
  console.log('size: ' + req.length());
  console.log('data: ' + req.toString());
  if (req.uri() == "/") req.response.sendFile("eventbusbridge/index.html")
  if (req.uri() == "/vertxbus.js") req.response.sendFile("eventbusbridge/vertxbus.js")
})
// Create a SockJS bridge which lets everything through (be careful!)
vertx.createSockJSServer(server).bridge({prefix: "/eventbus"}, [{}], [{}]);
server.listen(1234);

3) the receiver verticle code is:
var eb = require("vertx/event_bus");
var console = require("vertx/console");
eb.registerHandler("ping-address", function(message, replier) {
	console.log('message: ' + JSON.stringify(message));
	// Now reply to it
	var now = new Date();
        var ts = now.toISOString();
	replier('echo: ' + ts + ' ' + JSON.stringify(message));
});

chrome's console log looks like the following when the client remains running, and the two verticles comprising the event bus are stopped and restarted. the client connects before I transmit the mesage:
vertx-eventbus.system.disconnected
sockjs.js:807 GET http://127.0.0.1:1234/eventbus/info net::ERR_CONNECTION_REFUSED
angular.js:10072 [Vert.x EB Stub] Reconnect in 10000ms
cesiumModule.js:369 vertx-eventbus.system.disconnected
angular.js:10072 [Vert.x EB Stub] Connected
cesiumModule.js:364 vertx-eventbus.system.connected
cesiumModule.js:307 vertx no reply
cesiumModule.js:305 vertx echo received:  echo: 2015-02-26T13:30:47.883Z {"data":"2015-02-26T13:30:47.876Z test for echo [{\"facility\":\"location\"},{\"opcode\":11},{\"clientID\":\"kirk\"},{\"payload\":[[{\"id\":123},{\"label\":\"Label-One\"},{\"score\":99.5}],[{\"id\":456},{\"label\":\"Label-Two\"},{\"score\":23.7}],[{\"id\":789},{\"label\":\"Label-Three\"},{\"score\":0.9}]]}]"}

The two verticles are started in separate cmd tool windows with the -cluster option on the same host as the client -- on my desktop.

Lastly, the SockJSServer illustrates the following (the 647 length appears to indicate the reply which included the original message, plus a new timestamp):
Decoding WebSocket Frame length=511
Received msg from client in bridge. address:ping-address message:{"data":"2015-02-26T16:14:03.154Z test for echo [{\"facility\":\"st
ate college\"},{\"opcode\":11},{\"clientID\":\"kirk\"},{\"payload\":[[{\"id\":123},{\"label\":\"Label-One\"},{\"score\":99.5}],[{\"i
d\":456},{\"label\":\"Label-Two\"},{\"score\":23.7}],[{\"id\":789},{\"label\":\"Label-Three\"},{\"score\":0.9}]]}]"}
Forwarding message to address ping-address on event bus
Encoding WebSocket Frame opCode=1 length=647

The registered handler displays the following:
Succeeded in deploying verticle
message: {"data":"2015-02-26T16:14:03.154Z test for echo [{\"facility\":\"state college\"},{\"opcode\":11},{\"clientID\":\"kirk\"},{
\"payload\":[[{\"id\":123},{\"label\":\"Label-One\"},{\"score\":99.5}],[{\"id\":456},{\"label\":\"Label-Two\"},{\"score\":23.7}],[{\
"id\":789},{\"label\":\"Label-Three\"},{\"score\":0.9}]]}]"}

**Comment by Kirk-A** [comment]
corrected code except

**Comment by knalli** [comment]
Please have a look at the Markdown support for formatting the code ;)

> With the client running, after recycling the event bus (both verticles), the reply to client's first message immediately fails, triggering the catch function

A common mistake is sending messages when there is still no valid connection made. Are you sure the connection is already established? Alternatively `messageBuffer` would be helpful.

**Comment by knalli** [comment]
If you only want to make an initial request, you will probably consume the broadcast event for connected..?

**Comment by Kirk-A** [comment]
As shown in the console data above, during the recycle the connection is refused, then the connection is established (shown by both the FINER message logging and my own console message for the on() connection broadcast. Only then do I send the first message (that receives no reply). 

What seems to be interesting is that the timeout catch() is exercised immediately, not after waiting the timeout period. I wish I had more error info to go on...

Messages sent thereafter behave normally.

**Comment by knalli** [comment]
Can you provide an easy concept test only containing this specific case?

**Comment by Kirk-A** [comment]
I have produced a minimum test case and sent it to you, along with instructions to reproduce my results.

**Comment by knalli** [comment]
@Kirk-A  I've got your mail, but didn't have time for this. Will try to look into it today or so.

**Comment by knalli** [comment]
@Kirk-A  Finally, I had some time time to look into it.

Some notes and solutions for your problem:

1. I highly recommend you should use non minified source files at development stage and especially test cases. Just because the original source code directly shows you the context of a failure. Just my two cents, however.
2. You should not mixup AngularJS configuration phase with the regular phases. 
```js
// BAD / WRONG
var app = angular.module('yourmodule', []).controller('MyController', function () {
  app.config(function(someComponent) {
    someComponent.doStuff();
  });
});

// RIGHT
var app = angular.module('yourmodule', []);
app.config(function(someComponentProvider) {
  someComponentProvider.doStuff();
});

app.controller('MyController', function () {
});
```
In case of this demo, this is even really weird. That specific code could not work.

3. Sidenote: I'm not sure why this Date.prototype.toISOString polyfills are integrated. Are you not able to control the platform (i.e. vertx/java)?

4. There would be a timeout, but it is configured as `20ms` which is too less being noticed. After changing the corresponding line in the `vertxEventBusService.send`

```js
vertxEventBusService.send('ping-address', {data: ts + " test for echo " + tmpICD}, 1000).then(function(reply){
```

there will be well seen timeout again.

5. And now we are at the actual issue: No response. Well, it is no issue with angular-vertxbus, because I can fix this just with adding the `eb.registerHandler` right into `bridge_server.js`. That means, this is a server-side only issue.

After all, everything works.

```
[Vert.x EB Stub] Reconnect in 10000ms
todo.js:47 vertx-eventbus.system.disconnected
angular.js:10072 [Vert.x EB Stub] Connected
todo.js:43 vertx-eventbus.system.connected
todo.js:98 vertx echo received:  echo: 2015-03-10T20:51:34.104Z {"data":"2015-03-10T20:51:34.079Z test for echo [{\"facility\":\"state college\"},{\"opcode\":11},{\"clientID\":\"kirk\"},{\"payload\":[[{\"id\":123},{\"label\":\"Label-One\"},{\"score\":99.5}],[{\"id\":456},{\"label\":\"Label-Two\"},{\"score\":23.7}],[{\"id\":789},{\"label\":\"Label-Three\"},{\"score\":0.9}]]}]"}
```

Perhaps you had run into a similar issue like me a few moments ago.. the network adapters. You cluster.xml configuration *have to match* you actual in-use interface, otherwise both verticles will not found each other.

OK? Did I have overseen something, or was that your problem solved? :)
