### ISSUE TITLE
CORS issue on 80 port with https

### ISSUE THREAD

**Issue by Ignikot** [knalli/angular-vertxbus#39]
There are CORS error (tested in firefox), if protocol is "https" and page url app.site.com - urlServer evaluated as  app.site.com:80/
For https ":80" is error (":443" is better but in both cases ports can be omitted as default).

To fix it replace string 25 in https://github.com/knalli/angular-vertxbus/blob/master/src/wrapper.coffee
urlServer: "#{location.protocol}//#{location.hostname}:#{location.port or 80}"
with something like
urlServer: "#{location.protocol}//#{location.hostname}" + if location.port then ":#{location.port}"  else ""

**Comment by knalli** [comment]
Yep, fixed that. Thank you for the hint.
