### ISSUE TITLE
Compatibility with Vert.x 3.0

### ISSUE THREAD

**Issue by knalli** [knalli/angular-vertxbus#42]

**Comment by leolux** [comment]
Link to the current API of the bridge: https://github.com/vert-x3/vertx-apex/blob/master/src/client/vertxbus.js

**Comment by knalli** [comment]
Ok: I have opened https://github.com/knalli/angular-vertxbus/tree/feature/vertx3, and they are failing only the two login relevant tests.

I have not looked into it deep enough, perhaps I have to expose a login processing handler interface so anyone can implement on its own.

**Comment by leolux** [comment]
Hint: vertxbus.js has changed 2 hours ago by this change https://github.com/vert-x3/vertx-web/pull/105

**Comment by knalli** [comment]
I've added some work in a branch.

@leolux Are you familiar with v3 already? I need an authentication setup which would be a replacement for the old login/sessionId thing. Any ideas?

**Comment by knalli** [comment]
The branch contains a dedicated v3 installer (using latest M6, can be replaced by the final later the day).

**Comment by leolux** [comment]
In v3 I make use of the classes SessionHandler, UserSessionHandler, RedirectAuthHandler as well as my own implementation of the interfaces AuthProvider and FormLoginHandler. The authentication process changed in the way that the user first has to establish a valid login session with the HTTP server before any eventbus message will get allowed to pass through. I think that this is the new way that is prefered in vertx v3.

As far as I know there is currently no replacement for the authentication setup using the eventbus itself. Maybe we should just ask this question in the vertx forum to make sure.

Unfortunately I can't see a simple solution to this problem. I believe that it requires additional vertx code on the server side to handle authentication requests from the eventbus. It also means that you first have to upgrade to the websockets protocol before processing the actual login. But there were many changes in vertx 3 regarding authentication in the last couple of weeks. So there could be some chances it might not be too complicated.

**Comment by knalli** [comment]
@leolux  Ok, that means there is actually no replacement for the old `sessionID`. That one was injected in the raw envelope which is built in the EventBus internally (separated by the payload/message data). Right?

Said this, this library would be actually not in charge for authentication. Either the session is already qualified via HTTP, or you will have to establish a complete own strategy (like I did already in v2 because of a stateless and sessionless Vert.X nodes).

**Comment by leolux** [comment]
Yes, it's like you said. The Eventbus connection itself uses the TCP connection which was used to establish the websocket handshake before. So every eventbus connection runs within a TCP session. I am not sure if Vert.X nodes are stateless in the way that clients can establish websocket connections to any node sharing the same sessionId.

There are some additional thoughts about authentication in my mind which had been discussed in the topic around RESTful APIs. I will try to find them again to evaluate if they are relevant.

**Comment by leolux** [comment]
I found two aspects which might be interesting in this situation...
The sessionId is not transported within websocket frames in v3. Instead the session is derived from the session-cookie that is associated with the underlying socket connection. So there is no need to transport the sessionId on websocket frames anymore. However, I don't know how the session was identified in v2.

A new feature in v3 is that one can add headers in bridge event hooks. See https://github.com/vert-x3/vertx-web/commit/42d2a015fc4d65bfc6bf35f4d34eb44c7c2803e5
This should make it possible to implement any arbitrary complex logic.
