### ISSUE TITLE
vertxEventBus.send forces a replyHandler

### ISSUE THREAD

**Issue by leolux** [knalli/angular-vertxbus#49]
Vertxbus.js is able to send both messages that expect a reply and messages that expect no reply. Therefore it registers a reply handler only if possible:

```js
if (replyHandler) {
var replyAddress = makeUUID();
envelope.replyAddress = replyAddress;
replyHandlers[replyAddress] = replyHandler;
}
var str = JSON.stringify(envelope);
sockJSConn.send(str);
```

The problem is that the service vertxEventBus currently forces a message to expect a reply because it always passes a function to the last argument in line 538:
```js
           vertxEventBus.send(address, message, function(reply) {
              if (deferred) {
                return deferred.resolve(reply);
              }
            });
```
This will produce an exception on the server side for all messages that are not beeing replied:
io.vertx.core.eventbus.ReplyException: Timed out waiting for reply

**Comment by knalli** [comment]
Why do you not use publish?

**Comment by leolux** [comment]
Because I have clustered environment that collects statistical data. Publish would be a conceptional problem in this case.

**Comment by leolux** [comment]
I don't have experience in coffee script, so I hope that anyone else might also look into this.

**Comment by knalli** [comment]
> Because I use a clustered environment that collects statistical data. Publish would be a conceptional problem in this case.

Ehm.. `send()` is used returning a reply, but not `publish()`. Missing making the reply optional in case of `send()` is a defect in my adapter. 

But again: It sounds you are should use `publish()` anyway.

**Comment by leolux** [comment]
The difference between send() and publish() is a difference between point-to-point and publish-subscribe in the first place. If a node within a cluster is capable of doing a certain job autonomously why should I publish this job to all nodes? 

Tthank you for putting the issue into the queue.

**Comment by knalli** [comment]
See in 849eb3a

**Comment by leolux** [comment]
:leopard: Already finished? That is awesome! The change looks absolutely fine to me. 
Thx!

**Comment by knalli** [comment]
and. 1.1.0 available.
