### ISSUE TITLE
Exception at vertxEventBusService.removeListener() after reconnect

### ISSUE THREAD

**Issue by leolux** [knalli/angular-vertxbus#52]
In the current release 1.1.0 I get the following exception after the vertx server has rebooted:
Error: Parameter handler must be specified
    at checkSpecified (index.js:193)
    at vertx.EventBus.that.unregisterHandler (index.js:83)
    at Object.angular.module.provider.$get.EventBusStub.unregisterHandler (angular-vertxbus.js:223)
    at Object.angular.module.provider.$get.util.unregisterHandler (angular-vertxbus.js:547)
    at Object.angular.module.provider.$get.wrapped.unregisterHandler (angular-vertxbus.js:664)

Steps to reproduce:
1. start vertx server and client webapp
2. connect the client to the eventbus
3. register a listener and store the unregister-function somewhere
4. reboot the vertx server
5. wait for the client webapp to reconnect / listen to the "connected event"
7. handle that event and remove the privious listener by invoking vertxEventBusService.removeListener(address, unregisterfunction)

The exception occures every time these steps are finished, although the last parameter unregisterfunction is not undefined.

**Comment by knalli** [comment]
@leolux You are using the the plugin already for some time, I'm remembering. You have no problems with the 1.0.0?

I'll look into it later this day.

**Comment by knalli** [comment]
Ok. I have added in 4f2d763 an additional timer service for my "IT". I cannot see any problem here. What's the difference?

**Comment by knalli** [comment]
1. `npm run-script install-it-vertx-server` downloads and installs a Vert.X locally.
2. `npm run-script start-it-vertx-server` starts Vert.X on port 8080.
3. `npm run-script start-it-web-server` starts a web server on port 3000.
4. Open `http://localhost:3000/` in your browser.
5. Register the service TimerService
6. Restart 2.

**Comment by leolux** [comment]
I have tested version 1.0.0. just now. The error picture is almost identical:
Error: Parameter handler must be specified
    at checkSpecified (index.js:193)
    at that.unregisterHandler (index.js:83)
    at Object.EventBusStub.unregisterHandler (angular-vertxbus.js:204)
    at Object.util.unregisterHandler (angular-vertxbus.js:528)
    at Object.wrapped.unregisterHandler (angular-vertxbus.js:641)

**Comment by knalli** [comment]
@leolux Well, must be. Because between 1.0.0 and 1.1.0 was not changed anything in that area.

Can you show me the difference to the sample I've given (it) and yours?

**Comment by leolux** [comment]
Ok. I must setup your example first. I honestly don't know how to run this code/test.

**Comment by leolux** [comment]
Do I just have run the list of commands and steps you have described? I have npm and all that stuff installed already.

**Comment by knalli** [comment]
See here : https://github.com/knalli/angular-vertxbus/issues/52#issuecomment-91010216

**Comment by leolux** [comment]
On canary branch "npm run-script install-it-vertx-server" gives me this error:
> cd test/e2e/vertx && ./install.sh

Der Befehl "." ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe"
" "run-script" "install-it-vertx-server"
npm ERR! node v0.12.2
npm ERR! npm  v2.6.1
npm ERR! code ELIFECYCLE
npm ERR! angular-vertxbus@1.1.0 install-it-vertx-se
npm ERR! Exit status 1

**Comment by leolux** [comment]
I used my git bash to run this command

**Comment by knalli** [comment]
If you have the Git Bash installed, you can try to run the commands from this (its more unix/posix compatible).

Alternatively you have to reply the commands of the script.

**Comment by leolux** [comment]
test\e2e\vertx\install.sh: line 2: wget: command not found. I have to install wget first. I'll finish my test tomorrow.

**Comment by leolux** [comment]
wget seems to have some problems, even when running as administrator:
Kann nicht nach »b11d13e641e8115a8ffeff758626e950382d1a2d@response-content-disposition=attachment;filename=%22vert.x-2.1.1.tar.gz%
22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvYjExZDEzZTY0MWU4MTE1YThmZmVmZjc1
ODYyNmU5NTAzODJkMWEyZD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMnZlcnQueC0yLjEuMS50YXIuZ3olMjIiLC
JDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE0Mjg1MjU1Mzd9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn19
fV19&Signature=LpPvD7rM2vMnDhce5paywIOrsmpO~3dB1gLMO5OxaATjz44sk5EG1wQwAJtJDSk4oO2vYz~zU98UpcTR2ETbB8ISMx2Yk-yy1BEAhwBkktSTM1pQuJ-
iGvXzUlZFiNozhBLO~crv-eJ-PvnKGcfOJVUUrP8yHvw-O1OykqCXXFg7eNQkS9uzfwQkLwKkjz1R6oJPunUIU9p5Sm3e9dWyaMwZJ3F9yCq6z8ykV1SQ8K00Aikak9r3D
bLQM3PxtRZP1sPJNYtRvJf~3kGtbrSPZ6HZrOSZskwJDa3PSKAK5oe7U2cdlxLQhs~vs4PQfRCvkh1M9YGUWjDFRri1K6LP4Q__&Key-Pair-Id=APKAIFKFWOMXM2UMTS
FA« schreiben (Result too large).

**Comment by leolux** [comment]
Anyway. The difference to your example is that I unregister the previous listener explicitly in step 7 during hanling of the event "connected".

**Comment by knalli** [comment]
Ah, okay. That it is. During reconnect. Thanks.

**Comment by knalli** [comment]
@leolux  `1.1.1` released with the fix. Thank you for hint ;) The issue was already there for some time..

**Comment by leolux** [comment]
Running 1.1.1. produces the same exception 2 lines later:
Error: Parameter handler must be specified
    at checkSpecified (index.js:193)
    at vertx.EventBus.that.unregisterHandler (index.js:83)
    at Object.angular.module.provider.$get.EventBusStub.unregisterHandler (angular-vertxbus.js:224)
    at Object.angular.module.provider.$get.util.unregisterHandler (angular-vertxbus.js:549)
    at Object.angular.module.provider.$get.wrapped.unregisterHandler (angular-vertxbus.js:666)

**Comment by leolux** [comment]
In line 549 "callbackMap.get(callback)" evaluates to undefined:
    vertxEventBus.unregisterHandler(address, callbackMap.get(callback));

The parameter "callback" references the following function:
    function () {
            var index;
            if (unregisterFn) {
              unregisterFn();
            }
            if (wrapped.handlers[address]) {
              index = wrapped.handlers[address].indexOf(callback);
              if (index > -1) {
                wrapped.handlers[address].splice(index, 1);
              }
            }
            if (wrapped.handlers[address].length < 1) {
              wrapped.handlers[address] = void 0;
            }
          }

"

**Comment by knalli** [comment]
@leolux It would be helpful if you can specify the situation more precisely. 

Which calls are you invoking exactly? I need a difference between your setup and the provided IT (`npm run-script start-it-vertx-server` and `npm run-script start-it-web-server`) which works nicely. Perhaps a look into the client code (https://github.com/knalli/angular-vertxbus/blob/0bbc9c821834a204a5f4a06dfb2f4e300d04122d/test/e2e/web/app.js#L33-L43) is helpful too.

**Comment by leolux** [comment]
I've created a simple reproducer: https://github.com/leolux/angular-vertxbus_removelistener
The code of interest is this https://github.com/leolux/angular-vertxbus_removelistener/blob/master/src/main/resources/webroot/js/app.js

**Comment by knalli** [comment]
Thank you.

Ehm.. perhaps it was not clear enough (it is same pattern as in AJS):

```js
var unregisterfn = null;

function registerBusListener(vertxEventBusService) {
	unregisterfn = vertxEventBusService.on('inbound.test', function(message) {
		console.log('<<<<<<<<<< ', message);
	});
	console.log('Listener registered');
}

function unregisterBusListener(vertxEventBusService) {
	if (typeof unregisterfn === 'function') {
		vertxEventBusService.removeListener('inbound.test', unregisterfn);
		console.log('Listener unregistered');
	}
}
```

The last piece is wrong. The `unregisterfn` **is** the deconstructor.

```js
function unregisterBusListener(vertxEventBusService) {
	if (typeof unregisterfn === 'function') {
		unregisterfn();
		console.log('Listener unregistered');
	}
}
```

**Comment by leolux** [comment]
Ok, Thank you!
So if the unregisterfn() removes the listener from the map of handlers what is the method vertxEventBusService.removeListener() good for then?

**Comment by knalli** [comment]
```js
var callback = function () {};
vertxEventBusService.register('address', callback);
vertxEventBusService.unregister('address', callback);
```

**Comment by leolux** [comment]
There are still 2 issues with the unregisterHandler() function after a successfull reconnect. I updated the reproducer and added buttons to register and unregister. The two issues are marked in step 7 and 9.
https://github.com/leolux/angular-vertxbus_removelistener

**Comment by knalli** [comment]
what do you mean with "The two issues are marked in step 7 and 9" ?

**Comment by knalli** [comment]
Ah, got it.

**Comment by knalli** [comment]
Okay, the unregister function is invalid after using. I can add a guard for this prohibiting abuse.

**Comment by leolux** [comment]
Furthermore I don't understand the concept behind the registerHandler() function. Currently it is possible to register more than one handler for the same address which doesn't make much sens to me. For example a client that reconnects to the server after a server restart receives every message from the server twice because the reconnect itself automatically reconnects the intial handler and the client also registers a handler during the "connected" event.

Maybe we could distinguish between an "connected" event for initialization of the handlers and a new type of event like "reconnected" which tells the client to process further but without adding handlers again.

**Comment by leolux** [comment]
> Okay, the unregister function is invalid after using. I can add a guard for this prohibiting abuse.
This would solve issue 2 (step 9), but would it also solve the first issue in step 7?

**Comment by knalli** [comment]
Will have to run your project actually to confirm this issue. Later.

Atm I cannot confirm this, because my own tests do not have this issue (reconnect works, but deconstruction also)

**Comment by leolux** [comment]
Alright, thx.

**Comment by knalli** [comment]
> Furthermore I don't understand the concept behind the registerHandler() function. Currently it is possible to register more than one handler for the same address which doesn't make much sens to me. 

Why should a client not be able to listen to the same address twice? The client should not know a global state of active listeners.. ?!

> For example a client that reconnects to the server after a server restart receives every message from the server twice because the reconnect itself automatically reconnects the intial handler and the client also registers a handler during the "connected" event.

Well, you said it already. Do not register on reconnect. Register once and be happy.

**Comment by leolux** [comment]
I agree that a client can handle both connects and reconnects the correct way itself. But the thing is that a user of this adapter must take care of the difference between the initial connect event and the connect event after a reconnect itself because there is no separate event for this. If the user does not distinguish these scenarios, than the client accidentally receives messages twice. 

I think it would be more clear for users to have that distinction built into the API rather than. Maybe this could be an enhancement for a later release.

**Comment by knalli** [comment]
The point is: you can register for an address without being connected. That is the *thing* using `vertxEventBusService`.

**Comment by leolux** [comment]
> Why should a client not be able to listen to the same address twice?

I actually don't know if the client receives ttwo messages from the server or only one message that the client destributes to the listeners internally. If the server would send the message twice than it would waste resources.

**Comment by leolux** [comment]
> The point is: you can register for an address without being connected. 

That sounds nice. Didn't know about that yet.

**Comment by leolux** [comment]
Is there a difference between
```
var unregisterfn = null;

function registerBusListener(vertxEventBusService) {
    unregisterfn = vertxEventBusService.on('inbound.test', function(message) {
        console.log('<<<<<<<<<< ', message);
    });
}

function unregisterBusListener(vertxEventBusService) {
    if (typeof unregisterfn === 'function') {
        vertxEventBusService.removeListener('inbound.test', unregisterfn);
    }
}
```
> var callback = function () {};
vertxEventBusService.register('address', callback);
vertxEventBusService.unregister('address', callback);

**Comment by leolux** [comment]
Just to make it clear. Are both of the following ways supposed to do the same job of removing a listner?
1. 
´´´
var unregisterfn = null;

function registerBusListener(vertxEventBusService) {
    unregisterfn = vertxEventBusService.on('inbound.test', function(message) {
        console.log('<<<<<<<<<< ', message);
    });
}

function unregisterBusListener(vertxEventBusService) {
    if (typeof unregisterfn === 'function') {
        unregisterfn();
    }
}
´´´
2. 
> var callback = function () {};
vertxEventBusService.register('address', callback);
vertxEventBusService.unregister('address', callback);

**Comment by knalli** [comment]
Both: yes

**Comment by leolux** [comment]
Currently the situation looks like the first way contains one or two issues after a reconnect:
https://github.com/leolux/angular-vertxbus_removelistener
And the second way contains no issues both before and after a reconnect:
https://github.com/leolux/angular-vertxbus_removelistenerByCallback

**Comment by knalli** [comment]
Please try 1.1.2

**Comment by leolux** [comment]
I have updated https://github.com/leolux/angular-vertxbus_removelistener to use version 1.1.2. It seems to have fixed the second issue because the error does not occur anymore. Unfortunately the client still  receives messages from the server, although the button "Unregister" has been pushed after the reconnect.

**Comment by knalli** [comment]
Ok, found a bug: #55

New bugs please in a new issue. Thank you!
