### ISSUE TITLE
Ability to close the underlying SockJS connection using the service

### ISSUE THREAD

**Issue by leolux** [knalli/angular-vertxbus#54]
How to close the connection completely using vertxEventBusService? I can only see a close function on the EventBusStub.

**Comment by knalli** [comment]
Yep, that's right. The service itself does maintaining the connection (i.e. no reconnecting on service layer). If you really want to destroy the connection (why?), you will have to use `vertxEventBus.close()`. The service will be informed on any changes automatically.

**Comment by leolux** [comment]
It is just a functional requirement to destroy the connection at a specific point in time to prevent abuse of the system. 

One question though: How do I prevent vertxEventBusService to perform a reconnect after using vertxEventBus.close()?

**Comment by knalli** [comment]
An abuse of your system? You have opened the socket. I do not get it why you want to handle the socket connection, but anyway. It is up to you.

A reconnect can be disabled by setting `vertxEventBusProvider.useReconnect(false)` -- however, that will be a global configuration. Until now nobody had the need changing this at runtime.

As a workaround you can disable the reconnect feature and invoke `vertxEventBus.reconnect(true)`. Ideally wrapped into a dedicated component:

```js
angular.module('vertxbus-helper')
.config(function(vertxEventBusProvider) {
vertxEventBusProvider.useReconnect(false);
})
.factory('vertxEventBusConnectServiceHelper', function ($rootScope, vertxEventBus) {
  $rootScope.$on('vertx-eventbus.system.disconnected', function () {
    if (<you-want-reconnect>) {
      vertxEventBus.reconnect(true);
    }
  });
});
```

**Comment by leolux** [comment]
The system is designed as a one-time-only service type of thing. The connection should be destroyed at the end of the service process and should not be usable again. It would make more sense if I would explain the system in more detail, but that would not be relevant to others ;-)

**Comment by knalli** [comment]
Then stick with this solution. In general, everybody wants a simple connection forever. It's up to you utilizing the service and/or eventbus.

**Comment by leolux** [comment]
That's right. My system is the exception that proves the rule. Thank you for this nice workaround. I think that should do the trick.
