### ISSUE TITLE
Connect to several eventbus

### ISSUE THREAD

**Issue by HugoCrd** [knalli/angular-vertxbus#58]
Hi,

I got two eventbus, with two different URLs. How could I connect and use both of them?

Thanks for this module and your work ;)
Hugo

**Comment by knalli** [comment]
This is currently not a feature.

This is an interesting idea, but would require additional factory service to handle multiple instances of connections.

**Comment by manuknkra** [comment]
For which version you are planning to add this feature?

**Comment by knalli** [comment]
This is currently not active on any schedule. I had some work for the stability, authentication and other things.

I'm very happy for actual ideas how to implement this without loosing the simplicity of today.

**Comment by knalli** [comment]
Closing this. Nice idea, but the effort is too much. If someone will contribute, we can talk maybe.
