### ISSUE TITLE
Safari on OSX fail.

### ISSUE THREAD

**Issue by lzeligowski** [knalli/angular-vertxbus#59]
This is what we've got when running 2.0 version on Safari in OSX.

[Debug] [Vert.x EB Stub] Connected (angular.min.js, line 2972)
[Error] ReferenceError: Can't find variable: Symbol
	value (angular-vertxbus.js, line 4)
	value (angular-vertxbus.js, line 4)
	onopen (angular-vertxbus.js, line 4)
	onopen (angular-vertxbus.js, line 4)
	onopen (vertxbus.js, line 111)
	dispatchEvent (sockjs-1.0.0.min.js, line 2)
	_open (sockjs-1.0.0.min.js, line 2)
	_transportMessage (sockjs-1.0.0.min.js, line 2)
	(anonimowa funkcja) ([native code], line 0)
	emit (sockjs-1.0.0.min.js, line 2)
	onmessage (sockjs-1.0.0.min.js, line 3)

This is probably because of using "symbol.iterator" which is not supported by IE and Safari - line 882.

Take a look: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator

When using Chrome - there is no problem.

**Comment by knalli** [comment]
@lzeligowski Hm, perhaps I'd missed Safari but I thought it was working everywhere w/o the polyfill.

Can you please add the polyfill into your app and try again? https://babeljs.io/docs/usage/polyfill/

**Comment by lzeligowski** [comment]
Could you just write it down what should I do? I'm not an expert in JS world :D

**Comment by knalli** [comment]
I do not know your environment.

For example you can include the `browser-polyfill.js` from the `babel-core` npm package as it is explained in the link.

**Comment by lzeligowski** [comment]
Ok, I added in my index.html file.
Now - it works. Is there a chance you will fix your code that this file will be not required?

**Comment by knalli** [comment]
Now, that's required. But I'll provide an additional build with the polyfill. I'm on it, hold on..

**Comment by lzeligowski** [comment]
Super.
You're so fast... :D

**Comment by knalli** [comment]
2.0.2 released, see notes here: https://github.com/knalli/angular-vertxbus/blob/98afd11f462ba1d2c762276dc05c14493a777f10/README.md#javascript-polyfill
