### ISSUE TITLE
Compatibility question regarding angular-vertxbus.withpolyfill.js

### ISSUE THREAD

**Issue by leolux** [knalli/angular-vertxbus#62]
Does this alternative variant run on an ES5 browser or only on ES6?

**Comment by knalli** [comment]
A polyfill fixes the environment. Probably you need the version with polyfill unless

* you have such a polyfill already included
* you have no browser in support which supports only ES5

**Comment by leolux** [comment]
Ok, but I am still not sure what the variant withouth polyfill is good for.
I am new to polyfills. Do I need to integrate the polymere framework in order to get the bable-polyfill to work?

**Comment by knalli** [comment]
Again: The polyfill [fixes the environment](https://babeljs.io/docs/usage/polyfill/). I'm not aware of the Polymer framework regarding its ES5/ES6 compatibility. Probably you are ready if you have polyfill-webcomponents already included (as far as I found by a short search).

But if you are already using Polymer, you will probably not support old browsers? Eventually the  topic polyfills is not relevant for you..

**Comment by leolux** [comment]
So the standard version dist/angular-vertxbus.js already contains the environment fix?

**Comment by knalli** [comment]
@leolux _Why can't you use your eyes!_ ? :)

* angular-vertxbus.js standard w/o additional code
* angular-vertxbus.withpolyfill.js standard w/ additional polyfill (look at the filename)

**Comment by leolux** [comment]
Aha! Now I got it! 
Thanks for opening them^^
