### ISSUE TITLE
Emtpy string reply invokes failureHandler

### ISSUE THREAD

**Issue by leolux** [knalli/angular-vertxbus#63]
Since the update to 3.0.0 the failureHandler of vertxEventBusService.send() gets called instead of the replyHandler in case of an emtpy string reply. I haven't changed any code in my app so far.

And I haven't debugged the cause yet.

**Comment by leolux** [comment]
I will create an reproducer

**Comment by knalli** [comment]
Hm.. `vertxEventBus.send()` has already the [4th argument](https://github.com/knalli/angular-vertxbus/blob/8e5792c7b900ea6eb7a1be9ded0ddce3f0986ce6/src/lib/wrapper/Eventbus.js#L246-L250), but not the [service}(https://github.com/knalli/angular-vertxbus/blob/8e5792c7b900ea6eb7a1be9ded0ddce3f0986ce6/src/lib/service/delegate/Live.js#L244-L271). I wonder whoever is invoking the failureHandler when starting with the service...

**Comment by leolux** [comment]
I use the syntax as given by the readme:
```
vertxEventBusService.send('myaddress', {data: 123}, {timeout: 3000})
  .then(function(reply) {
    console.log('A reply received: ', reply);
  })
  .catch(function() {
    console.warn('No message within 3 seconds'); // <-------------- this function gets invoked
  });
```
My reproducer is ready and shows that there is an issue before your wrapper:
https://github.com/leolux/vertx-eventbusbridge-emptyreply

**Comment by leolux** [comment]
The issue is no tracked at  https://github.com/vert-x3/vertx-web/issues/186

**Comment by knalli** [comment]
Perhaps the reply must be a JSON (and a string is not qualified) always?

**Comment by leolux** [comment]
No, JSON is not an requirement. The issue is now fixed in the latest maste version https://github.com/vert-x3/vertx-web/blob/master/src/client/vertxbus.js

**Comment by knalli** [comment]
@leolux  Yes thanks. I'd already subscribed the issue. Waiting for the release also.

**Comment by leolux** [comment]
I am using bower for my app. So I think that I could patch vertxbux.js by overriding the "main" attribute of "angular-vertxbus". Do you know a better way to patch files in a web project?

**Comment by knalli** [comment]
You define the override itself in your `bower.json`, i.e. 

```json
{
  "dependencies": {
    "vertx3-eventbus-client": "~3.0.1"
  }
}
```

or in case of a special commit ref

```json
{
  "dependencies": {
    "vertx3-eventbus-client": "https://github.com/vert-x3/vertx-web.git#11f3b430a0deeeaf3603cd78394a5488300d34ce"
  }
}
```

(command `bower install https://github.com/vert-x3/vertx-web.git#11f3b430a0deeeaf3603cd78394a5488300d34ce`)
