### ISSUE TITLE
Documentation of configuration options

### ISSUE THREAD

**Issue by leolux** [knalli/angular-vertxbus#64]
Where to find the documentation about all these options?

 vertxEventBusProvider
        .enable()
        .useReconnect()
        .useUrlServer(wsEndpoint)
        .useUrlPath(wsPath)
        .useSockJsOptions(options); // <------------ especially about this object

**Comment by knalli** [comment]
Ehm.. these are special SockJS options. Have a look at https://github.com/sockjs/sockjs-client#sockjs-client-api

**Comment by leolux** [comment]
Alright, thanks! The changed the options name from "protocols_whitelist" to "transports". That cause my confision about xhr request where the whitelist contains only websocket...

**Comment by knalli** [comment]
Ah, because v3 upgrades the underlaying SockJS also.
