### ISSUE TITLE
Reply undefined

### ISSUE THREAD

**Issue by leolux** [knalli/angular-vertxbus#65]
Currently my client receives an undefined reply in the replyHandler of the vertxEventBusService when the server replies with message.fail(0, "error message").

I am confused why the failureHandler does not get invoked when the server sends a failure response.

**Comment by knalli** [comment]
@leolux  You have to elaborate this a bit. :)

And you are still aware of the service not supporting the failureHandler? https://github.com/knalli/angular-vertxbus/blob/8e5792c7b900ea6eb7a1be9ded0ddce3f0986ce6/src/lib/service/delegate/Live.js#L256

**Comment by leolux** [comment]
I expected it to work because I mixed it up with the following bugfix https://github.com/vert-x3/vertx-web/commit/909f5b283788d2870ebf721b9462aa1d7970164b

In which release could we expect the failureHandler to work?

**Comment by knalli** [comment]
Perhaps with v4 (next major can break). I'm quite not sure about the implications of #76.
