### ISSUE TITLE
Vertx login example

### ISSUE THREAD

**Issue by rszczypka** [knalli/angular-vertxbus#66]
Hi,
I'm really interested in a real-live example or a snippet of the vertx login implementation with your `vertxEventBusService`. 

Also, how do you use the `ensureOpenAuthConnection(fn)` method?

Thanks! Rafal

**Comment by knalli** [comment]
You will find e2e tests described at https://github.com/knalli/angular-vertxbus#e2e-tests-manually

Alternatively, you can use `install-it-vertx3-server` and `start-it-vertx3-server` installing and serving a Vert.x.
