### ISSUE TITLE
choose vertx-server / server-adress during runtime?

### ISSUE THREAD

**Issue by TeilZeitMensch** [knalli/angular-vertxbus#71]
Is there a way, to choose / configure the URL Server during runtime?
So far, i only see the possibility to use .useUrlServer() on the provider configuration to set the address of the vertx server, but my entry to my application is a possibility to choose one of some different servers.

Is there a possibility or a hack, to "change" server url?

**Comment by knalli** [comment]
At the moment that is not possible , since the connection will/should/must be created asap.

Perhaps it would be a nice feature request of a somehow config provider instance…Also the connection/setup must be deferred.

Well.. feature request => contributions are welcome :)

**Comment by erhard** [comment]
Hello Jan,

is it possible to use wss somehow ?
I have no Idea to tell Vertx::Eventbus to use wss. Does the client react accordingly ?

Background of the question is :

I read that for mobile devices websocket often are blocked. A wss connection is initialized from a https connection and not recognized from many proxies as a ws connection.



Thanks for any reply 

Erhard

**Comment by knalli** [comment]
@erhard Please don't hijack other topics.

Anyway: Just setup a connection with a https, the upgrade to wss will be made by the SockJS server (port of Vert.x) automatically. This has actually nothing to do with angular-vertxbus.. even EventBus/SockJS relies on Http-to-WebSocket-Upgrading.

**Comment by knalli** [comment]
Available in 3.1 (ce3a0af)

**Comment by TeilZeitMensch** [comment]
Really cool. Than i could update my App, and try this.
