### ISSUE TITLE
Fallback to longPolling via http ?

### ISSUE THREAD

**Issue by erhard** [knalli/angular-vertxbus#78]
I have an application which runs in the browser like a charm with angular-vert-bus. Running in cordova on android it does not get the asynchronous reply from my verticles. (The server receives the first call, sends out the assent reply, but my client does not get it) Even in the phone chrome browser it works.
Is there a possibility to force the fallback ? (If there is one)

Thanks

Erhard

**Comment by erhard** [comment]
Perhaps this helps ... I fire to the server and get a synchron response the it has got the request.
This work. Then business logic DB Request and so on are made the results packed in a json and fired to the client now asynchronous. This does not come to the client on cordova. On The Desktop it works. I just wonder before I updated (new android new angular-vertxbus new vertx version new cordova) it worked.  I try to verify this by finding an old version of my client.
Is websockets a technology at all for phones ?

**Comment by knalli** [comment]
@erhard I'm only providing the high level api wrapping the existing _EventBus_ over _ SockJS_ over _WebSocket/HTTP_ stack. I simply cannot solve any of the underlaying problems.. I'm not in charge.

However, given you last question: It depends. WebSocket should be available in most current devices but could be buggy in older. Also you should be aware a physical socket connection will likely drop/reconnect on mobile devices due their nature of existence. In that case, the automatic fallback to XHR/long polling it eventually the result. You have to control this in your SockJS settings both on server and on client side.

In general, there is no issue a WebSocket should not work on mobile devices within a Cordova webview.
