### ISSUE TITLE
How to handle fail for a send

### ISSUE THREAD

**Issue by rszczypka** [knalli/angular-vertxbus#96]
I'm using `vertxEventBusService.send("login", data).then(function(reply){console.log(reply)})`

But I wonder how to handle the response when the server replies with `fail(int failureCode, String message)`?

**Comment by knalli** [comment]
If `fail()` is the `failureHandler`: this will be possible in the [future](https://github.com/knalli/angular-vertxbus/blob/43626aade7b49abccf2f5609c30589ef66bf78c9/src/lib/service/delegate/EventBusDelegate.js#L256). Perhaps someone comes up with a dual solution. At the moment I don't want to drop v2 support.

If you mean a general error.. just use the failure callback of the promise: `~.send(…).then(success, failure)`.

And if you are really have to use the `failureHandler`, you can use the `vertxEventBus` adapter directly: https://github.com/knalli/angular-vertxbus/blob/43626aade7b49abccf2f5609c30589ef66bf78c9/src/lib/adapter/EventBusAdapter.js#L272

**Comment by rszczypka** [comment]
Thanks a lot. I just tried with `vertxEventBus` and it works well. 
Is there any benefit in using `vertxEventBusService` to `vertxEventBusService` in this case?

**Comment by knalli** [comment]
@rszczypka Glad to here. Please follow https://github.com/knalli/angular-vertxbus#architecture-details
